### ISSUE TITLE
Can I reformat your README.MD....?

### ISSUE THREAD

**Issue by remghoost** [decrazyo/lng-fds#2]
Freaking cool project. I find your `README.MD` a bit challenging to read though.

Would you be interested in me reformatting it with markdown...?

I'm not asking for money or anything, just wanted to know if it was something you were interested in before starting on it.

[Here's an example of my markdown-ing from a pull request.](https://github.com/aliparlakci/bulk-downloader-for-reddit/pull/940) 

[Here's an example from one of my repos.](https://github.com/remghoost/prompt-randomizer)

[And here's an example from reddit.](https://www.reddit.com/r/facepalm/comments/1ahehmp/comment/koon0vu/?context=3) 
Though reddit markdown is a bit different (note that it doesn't have linebreaks).

I can embed pictures into it as well (if you wanted to take a few of it running on a console), to give people a feel for what it looks/acts like.

It might help grow your userbase/audience a bit more. 
I'd love to see a project like this freaking go for the moon.

**Comment by bootmii** [comment]
This could have been a pull request.
